name: Cherry Pick and Tag

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA(s) to cherry-pick'
        required: false
      version:
        description: 'Version number for branch and tag'
        required: true

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create or checkout branch
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/releases/v${{ github.event.inputs.version }}; then
            git checkout releases/v${{ github.event.inputs.version }}
          else
            git checkout -b releases/v${{ github.event.inputs.version }}
          fi

      - name: Cherry-pick commits
        run: |
          IFS=',' read -ra COMMITS <<< "${{ github.event.inputs.commit }}"
          for i in "${COMMITS[@]}"; do
            git cherry-pick $i
          done
        if: ${{ github.event.inputs.commit }}

      - name: Push changes
        run: |
          git push origin releases/v${{ github.event.inputs.version }}

      - name: Create or update tags
        run: |
          IFS='.' read -ra VERSIONS <<< "${{ github.event.inputs.version }}"
          TAG=""
          for i in "${VERSIONS[@]}"; do
            if [ -z "$TAG" ]; then
              TAG="$i"
            else
              TAG="$TAG.$i"
            fi
            git tag -f v$TAG
            git push -f origin v$TAG
          done
